{
 "title": "Home Assistant",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Temperature & Humidity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Upstairs Landing Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "dht_temp" }
     ]
    },
    {
     "alias": "Upstairs Office Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "temperature" }
     ]
    },
    {
     "alias": "Dark Sky Outside Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "°C",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "dark_sky_temperature" }
     ]
    },
    {
     "alias": "Upstairs Inside Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "humidity" }
     ]
    },
    {
     "alias": "Dark Sky Outside Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "%",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "dark_sky_humidity" }
     ]
    }
   ]
  },
  {
   "title": "Motion State",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Landing Motion Sensor State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensor.motion",
     "select": [
      [
       { "params": [ "friendly_name_str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "motion" }
     ]
    },
    {
     "alias": "Camera Motion Sensor State",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "binary_sensor.dafang_motion_sensor",
     "select": [
      [
       { "params": [ "friendly_name_str" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "binary_sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "dafang_motion_sensor" }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "alias": "$tag_entity_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity_id" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "m/s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=", "value": "sensor" },
      { "condition": "AND", "key": "entity_id", "operator": "=", "value": "dark_sky_wind_speed" }
     ]
    }
   ]
  }
 ]
}