# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name postarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: postarr-secret
    template:
      data:
        rclone_sa.json: '{{ .RCLONE_SA }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: postarr
