---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app postarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      postarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/zarskie/postarr
              tag: develop@sha256:9a2b94b6b365f6d3fa28b85be4ef44d1ef98e1c9f257dd13f487a1a1d03f2993
            env:
              TZ: "${TZ}"
              PUID: "1000"
              PGID: "1000"
              MAIN_LOG_LEVEL: "debug"
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"], add: ["CHOWN", "SETUID", "SETGID"] }
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: posteria.png
          gethomepage.dev/name: Postarr
        hostnames:
          - "{{ .Release.Name }}.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: *app
      assets:
        type: nfs
        server: duriel.internal
        path: /tank/Media/postarr/assets
        globalMounts:
          - path: /assets
      posters:
        type: nfs
        server: duriel.internal
        path: /tank/Media/postarr/posters
        globalMounts:
          - path: /posters
      rclone-sa:
        type: secret
        name: postarr-secret
        globalMounts:
          - path: /config/rclone_sa.json
            subPath: rclone_sa.json
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /config/logs