---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-ai-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        PAPERLESS_API_TOKEN: "{{ .PAPERLESS_API_TOKEN }}"
        CUSTOM_API_KEY: "{{ .LITELLM_API_TOKEN}}"
  dataFrom:
    - extract:
        key: paperless-ai
