---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ai
  namespace: ai
  labels:
    app.kubernetes.io/name: &name paperless-ai
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
