# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pikvm
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: pikvm-secret
    template:
      data:
        username: admin
        password: '{{ .PIVM_PROMETHEUS_PASSWORD }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: kube-prometheus-stack
