---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app toolhive-operator
  namespace: ai
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: toolhive-operator
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    operator:
      replicaCount: 1
      gc:
        gomemlimit: 450MiB
        gogc: 75
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 500m
          memory: 1Gi
