---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deduparr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: deduparr-secret
    template:
      data:
        DEDUPARR_RADARR_MOVIES_API_KEY: '{{ .RADARR__API_KEY }}'
        DEDUPARR_SONARR_SERIES_API_KEY: '{{ .SONARR__API_KEY }}'
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: arrs