---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-mcp
  namespace: ai
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: '{{ .GITHUB_PERSONAL_ACCESS_TOKEN }}'
  dataFrom:
    - extract:
        key: github-mcp
