---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
components:
  - ../../flux/components/common
resources:
  - ./litellm/ks.yaml
  - ./llmkube/ks.yaml
  - ./memini/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless-ai/ks.yaml
  - ./searxng/ks.yaml
  - ./text-embeddings/ks.yaml
