---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: talos
  namespace: ai
spec:
  image: registry.erwanleboucher.dev/eleboucher/talos-mcp:0.0.2
  transport: streamable-http
  proxyMode: streamable-http
  proxyPort: 8080
  mcpPort: 8080
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: TALOS_MCP_TRANSPORT
      value: http
    - name: TALOS_MCP_HTTP_ADDR
      value: ":8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - name: talosconfig
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
      volumes:
        - name: talosconfig
          secret:
            secretName: talos-mcp-talosconfig
            defaultMode: 0400
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
